### PR TITLE
feedback model is created and api to submit and retrieve

### LINKED ISSUE #29: [Server] Implement Feedback API routes
## Feedback & Reviews
**Description:**  
Allow users to provide feedback and rate quizzes after completion.

**Tasks:**
- Create feedback model.
- Implement routes for submitting and retrieving feedback.
- Integrate feedback with quiz results to allow users to leave reviews after completion.

**Dependencies:**  
- **Quiz Management** (Issue 2) since users will be reviewing quizzes.

**Guidelines for Assignee:**
- Comment on the issue with the feedback model and the routes for submitting/viewing feedback.

### PR DESCRIPTION
**Pull request by Avinashs7**
Fixes #29 Implement Feedback API routes 

## Description
- Feedback model is created with rating and comments with userId and quizId.
- Built API for submitting the feedback and also to retrieve it.
- Tested the routes using postman.

## API's:
- POST feedback/quiz/:quizId  
To post a feedback for a particular quiz
- GET feedback/quiz/:quizId
To retrieve the feedback for a given quiz ID
- GET feedback/user 
To retrieve all the feedbacks given by a particular user.

Commit: 5e8c04c08ca5d18f0c60e02111b9a7f4f650e9eb
Author: Avinashs7
Date: 05/10/2024

### CODE REVIEW

**Comment by shubhansu-kr** [comment]
@Avinashs7 Thank you for contributing. Can you please share testing details with postman responses here.

**Comment by shubhansu-kr** [comment]
Changes look good to me.

**Comment by Avinashs7** [comment]
> @Avinashs7 Thank you for contributing. Can you please share testing details with postman responses here.

@shubhansu-kr Note:
There isn't a quiz model hence in feedback model quiz ID was been made as String for testing purpose only. Other than that everything else is intact.
 
 ## Submitting feedback route. The user must have signed in since it has authorization header:
Screenshot 2024-10-05 171337

## Retrieving all the feedbacks for a given quiz ID:
Screenshot 2024-10-05 171424

## Retrieving all the feedbacks given by an User using userId:
Screenshot 2024-10-05 171528

I have added all the three routes working above.

**Comment by shubhansu-kr** [comment]
Thank you for your contribution @Avinashs7 .

**Pull request merged**
