### PR TITLE
Added Quiz creation page with minimal styling 

### LINKED ISSUE #50: [FEATURE] Create the quiz creation page.
### **Additional Context**
*  Look into the UI design inspo at https://www.figma.com/design/s0eI8YDamF3Gqh3Bt5et99/asmbDev?node-id=116-4&t=IzEZnyEPebG9bJvh-1
* Make it like in the design or better
* Make it responsive
* Use framer motion for animating the page's load/unload to make the UI more user friendly.
* Color code of dark mode and light mode for button, bg, text has been set up in the <code>tailwind.config.js</code> file, changing it will create inconsistency in the UI.
* example of using the color code : <code>className="bg-radial-light dark:bg-radial-dark"</code> this className changes according to the theme.
* this page should be visible when the user visits the <code>/create</code> route.
* Once created add the details in <code>documentation.md</code>, look for it in <code>server/documentation.md</code>

### PR DESCRIPTION
**Pull request by Avinashs7**
# Fixes issue #52  .

## Overview 
  - Quiz creation route has been updated and also As I have mentioned, I have created the quiz form with minimal styling.
  - It accepts the as many question you want to add and also each question has a multiple options addition.
  - The correct option is given select box to select within the given option.
  - The submit will store the quiz questions with the user as author (I have used context API for API calls).
  - Partially fixes #50 
  
## Future enhancement 
  - Fix the style as designs given in issue #50 
  - Has some minor bugs in server should refactor it

@shubhansu-kr Check with the import in server, While solving this issue came across the importing models wrongly and I have fixed while solving this also.
And also raise the issue wrt design as I have built a bare framework of quiz creation 

Commit: d3de7caf581bbda2171001fc10fa3e4384a3e8cb
Author: Avinash S
Date: 25-10-2024

### CODE REVIEW

**Comment by shubhansu-kr** [comment]
@Avinashs7 Any screenshot showing the end result ?

**Comment by shubhansu-kr** [comment]
Can you please fix the commit trail ? I see you created another PR which has 3 of the commits you made here . Create a seperate branch for each feature or change to avoid these conflicts .

**Comment by shubhansu-kr** [comment]
@Avinashs7 Thanks for contributing

**Comment by Avinashs7** [comment]
## End result Screenshots 
The current status doesn't has the redirection after accepting the quiz, I purposefully left to handle once the page design completion, Also you can notice that I manually put the jwt to local storage (for authorizing the user), I want this to be done by the person handling the signup/login feature #57. If incase the contributor chose to use cookies or any other storage in the browser, It needs to be updated in the API call (headers in quizContext).
API endpoint for backend needs to be done in frontend using `.env` and I have given `.env.sample` file for reference

## Intial state of DB:
Screenshot 2024-10-26 054333

## Intial form rendering:
Screenshot 2024-10-26 054347

## The form has feature to give as many option user wishes to and has to select the correct answer from the given option, to handle the inconsistency
Screenshot 2024-10-26 054511

## The DB end results.
Screenshot 2024-10-26 054549

**Comment by Avinashs7** [comment]
@shubhansu-kr Sorry for messing up the commit trail, I had raised PR of another issue after that, I created new branch but it was already ahead of main didn't notice that time.
Thanks! for understanding and resolving it. I move forward with this learnings and take care of not doing the same mistake.

**Pull request merged**
