### PR TITLE
Added Api Routes for Badges and Achievements

### LINKED ISSUE #28: [Server] Implement achivements and badges API routes.
## Gamification Features (Badges, Achievements)
**Description:**  
Implement a gamification system where users can earn badges and achievements based on their quiz performance and participation.

**Tasks:**
- Create badge/achievement model.
- Implement routes to fetch and update user achievements.
- Implement logic to award badges for specific actions (e.g., quiz completion, high scores).

**Dependencies:**  
- **Quiz Management** (Issue 2) and **Polls & Voting** (Issue 3) for tracking user actions.
- **Leaderboard** (Issue 4) for tracking high scores.

**Guidelines for Assignee:**
- Comment on the issue with the model and rules for awarding badges/achievements.

### PR DESCRIPTION
**Pull request by Trishank-K**
# Pull Request Description Guidelines

To ensure the quality and maintainability of the codebase, each assignee is required to follow these guidelines when submitting a Pull Request (PR). This will help reviewers understand the scope of your changes, verify that nothing is broken, and assess the impact on the project. This PR 'closes #28'

## PR Description Requirements:
1. **Overview of Changes**:
   - Modified the user Schema to include Badges and Achievements and References.
   - The badges and achievements Schema looks similar to [this](https://github.com/mvp-2003/Quikz/issues/28#issuecomment-2394053970) with a slight change
   - Earlier the achievements were references of badges but here these are two seperate entities and can have independent criterias.

2. **Documentation**:
   - All the changed api routes have been updated in Documentation.md
   
3. **Breaking Changes**:
   - Since the user schema has changed to include references of badges and achievements, it might cause issues if there are any existing users already.
   - A query to modify the existing users' schema having a differnet resemblance will fix the issue.

4. **Assumptions & Decisions**:
   - It has been assumed that the admin has a non-compromised email id which will act as validation of admin.
   - The email is set as a environment variable.
   - If in future the validation criteria is to be changed that can be done by changing the body parameters.

5. **Testing Details**:
   - All tests have been performed using postman

6. **Screenshots (if applicable)**:
   - Get all Badges
image
   - Create an achievement
image
   - Award User an achievement
image
   - Delete an achievement
image

**All the api routes provide for badges are similar for achievements and vice versa**

8. **Checklist**:
   - [X] All relevant documentation is updated.
   - [X] No breaking changes or documented if any.
   - [X] Testing details provided, with tests added where necessary.
   - [X] Screenshots or media attached (if applicable).
   - [X] PR is linked to the corresponding issue(s).

### CODE REVIEW

**Comment by shubhansu-kr** [comment]
Nevermind, I resolved. May cause outage. Will fix later.

**Comment by Trishank-K** [comment]
hey @shubhansu-kr apologies for not linting the code properly.
Hopefully won't cause any outages 🤞

**Comment by shubhansu-kr** [comment]
No worries. There is an unassigned issue. If you would like to contribute you can check that

**Comment by Trishank-K** [comment]
hey @shubhansu-kr I have pinged you there
please check

**Pull request merged**
