### PR TITLE
feat: Add tag model and routes

### LINKED ISSUE #30: [Server] Implement Tags & Categories API routes
## Tags & Categories
**Description:**  
Implement tags and categories to organize quizzes, polls, and questions for better user filtering and search capabilities.

**Tasks:**
- Create tags/categories model.
- Implement routes to create and manage tags/categories.
- Integrate tagging into quiz and question creation to allow for easier filtering.

**Dependencies:**  
- **Quiz Management** (Issue 2) and **Question Bank** (Issue 5) for tagging quizzes and questions.

**Guidelines for Assignee:**
- Comment on the issue with the model and routes for tagging.
- Follow RESTful conventions for filtering routes.

### PR DESCRIPTION
**Pull request by Horsmanayo**
- Added new file `tag.js` in `src/server/models` to define the tag schema and create the `Tag` model.
- Added new file `tagRouter.js` in `src/server/routes` to handle tag-related API endpoints.
- Implemented CRUD operations for tags in `tagController.js`.
- Updated `quizRouter.js` to include a new route for getting all tags.

Closes #30

# Pull Request Description Guidelines

To ensure the quality and maintainability of the codebase, each assignee is required to follow these guidelines when submitting a Pull Request (PR). This will help reviewers understand the scope of your changes, verify that nothing is broken, and assess the impact on the project.

## PR Description Requirements:
1. **Overview of Changes**:
   - Provide a high-level summary of the changes made.
   - Include references to the specific issue(s) the PR addresses.

2. **Documentation**:
   - Describe how the feature or change is documented.
   - Provide a link or reference to the updated documentation (e.g., `Documentation.md` or in-line comments).
   
3. **Breaking Changes**:
   - Clearly state if there are any breaking changes or if it impacts existing functionality.
   - Provide details on how to migrate or adapt any affected areas.

4. **Assumptions & Decisions**:
   - Share any key assumptions or decisions made during development that others should be aware of.
   - Mention any workarounds or decisions that may impact future implementations.

5. **Testing Details**:
   - Include a list of tests performed (unit tests, integration tests, etc.).
   - Add any relevant code coverage reports, screenshots of test results, or other testing-related artifacts.

6. **Screenshots (if applicable)**:
   - Provide screenshots or videos to demonstrate new UI elements or to show behavior changes, if applicable.

7. **Checklist**:
   - [x] All relevant documentation is updated.
   - [x] No breaking changes or documented if any.
   - [x] Testing details provided, with tests added where necessary.
   - [x] Screenshots or media attached (if applicable).
   - [x] PR is linked to the corresponding issue(s).

### CODE REVIEW

**Comment by Horsmanayo** [comment]
Screenshot 2024-10-08 at 7 24 45 AM
Screenshot 2024-10-07 at 11 21 32 PM
Screenshot 2024-10-08 at 7 24 45 AM
Screenshot 2024-10-08 at 8 32 33 AM

1. Shows creating tag
2. Shows getting all tags 
3. Shows deleting a tag 
4. Shows filtering  quiz by tag id

**Comment by shubhansu-kr** [comment]
Please resolve conflicts @Horsmanayo and run es lint

**Comment by Horsmanayo** [comment]
@shubhansu-kr All done, you can review now

**Comment by shubhansu-kr** [comment]
Thank you for your contribution @Horsmanayo

**Pull request merged**
